spring:
  datasource:
    username: root
    password: SZYjsw142590
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://47.97.255.9:3306/safe_resume

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

ipfs:
  multiaddr: /ip4/47.97.255.9/tcp/6001

