spring:
  datasource:
    username: root
    password: SZYjsw142590
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://47.97.255.9:3306/safe_resume

ipfs:
  multiaddr: /ip4/47.97.255.9/tcp/6001
#  ipfs_host: http://47.97.255.9:6001
#  ipfs_url_upload: ${ipfs_host} + "/api/v0/add"
#  ipfs_url_download: http://47.97.255.9:8080/ipfs/
